apiVersion: v1
kind: Configmap
metadata:
  name: mysql-init
data:
  init_sql: |
  CREATE USER IF NOT EXISTS "root"@"%" IDENTIFIED BY "root";
  GRANT ALL PRIVILEGES ON *.* TO "root"@"%" WITH GRANT OPTION;
  
  CREATE USER IF NOT EXISTS "fatec"@"%" IDENTIFIED BY "fatec";
  GRANT ALL PRIVILEGES ON db_bibilioteca.* TO "fatec"@"%";
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATAVASE
              value: "db_biblioteca"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
              name: init-script
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: mysql_storage
          persistentVolumeClaim: 
            claimName: mysql-pvc
        - name: init-script
          configMap: 
            name: mysql-init

apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      NodePort: 3306
  selector:
    app: mysql


